export const LendingPoolAbi = [
    {
      type: "constructor",
      inputs: [{ name: "_router", type: "address", internalType: "address" }],
      stateMutability: "nonpayable",
    },
    { type: "fallback", stateMutability: "payable" },
    { type: "receive", stateMutability: "payable" },
    {
      type: "function",
      name: "borrowDebt",
      inputs: [
        { name: "_amount", type: "uint256", internalType: "uint256" },
        { name: "_chainId", type: "uint256", internalType: "uint256" },
        { name: "_dstEid", type: "uint32", internalType: "uint32" },
        {
          name: "_addExecutorLzReceiveOption",
          type: "uint128",
          internalType: "uint128",
        },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "checkLiquidation",
      inputs: [{ name: "borrower", type: "address", internalType: "address" }],
      outputs: [
        { name: "isLiquidatable", type: "bool", internalType: "bool" },
        { name: "borrowValue", type: "uint256", internalType: "uint256" },
        { name: "collateralValue", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "liquidateByDEX",
      inputs: [
        { name: "borrower", type: "address", internalType: "address" },
        {
          name: "liquidationIncentive",
          type: "uint256",
          internalType: "uint256",
        },
      ],
      outputs: [
        { name: "liquidatedAmount", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "liquidateByMEV",
      inputs: [
        { name: "borrower", type: "address", internalType: "address" },
        { name: "repayAmount", type: "uint256", internalType: "uint256" },
        {
          name: "liquidationIncentive",
          type: "uint256",
          internalType: "uint256",
        },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "repayWithSelectedToken",
      inputs: [
        { name: "shares", type: "uint256", internalType: "uint256" },
        { name: "_token", type: "address", internalType: "address" },
        { name: "_fromPosition", type: "bool", internalType: "bool" },
        { name: "_user", type: "address", internalType: "address" },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "router",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "supplyCollateral",
      inputs: [
        { name: "_amount", type: "uint256", internalType: "uint256" },
        { name: "_user", type: "address", internalType: "address" },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "supplyLiquidity",
      inputs: [
        { name: "_user", type: "address", internalType: "address" },
        { name: "_amount", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "withdrawCollateral",
      inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "withdrawLiquidity",
      inputs: [{ name: "_shares", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "event",
      name: "BorrowDebtCrosschain",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "shares",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "chainId",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "addExecutorLzReceiveOption",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "CreatePosition",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "positionAddress",
          type: "address",
          indexed: false,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "InterestRateModelSet",
      inputs: [
        {
          name: "oldModel",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "newModel",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "RepayByPosition",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "shares",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "SupplyCollateral",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "SupplyLiquidity",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "shares",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "WithdrawLiquidity",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "shares",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    { type: "error", name: "InsufficientBorrowShares", inputs: [] },
    { type: "error", name: "InsufficientCollateral", inputs: [] },
    { type: "error", name: "InsufficientContractBalance", inputs: [] },
    { type: "error", name: "InsufficientLiquidity", inputs: [] },
    { type: "error", name: "InsufficientShares", inputs: [] },
    {
      type: "error",
      name: "InvalidOptionType",
      inputs: [{ name: "optionType", type: "uint16", internalType: "uint16" }],
    },
    { type: "error", name: "InvalidParameter", inputs: [] },
    { type: "error", name: "LTVExceedMaxAmount", inputs: [] },
    {
      type: "error",
      name: "NotAuthorized",
      inputs: [{ name: "executor", type: "address", internalType: "address" }],
    },
    { type: "error", name: "NotOperator", inputs: [] },
    { type: "error", name: "PositionAlreadyCreated", inputs: [] },
    { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
    {
      type: "error",
      name: "SafeCastOverflowedUintDowncast",
      inputs: [
        { name: "bits", type: "uint8", internalType: "uint8" },
        { name: "value", type: "uint256", internalType: "uint256" },
      ],
    },
    {
      type: "error",
      name: "SafeERC20FailedOperation",
      inputs: [{ name: "token", type: "address", internalType: "address" }],
    },
    { type: "error", name: "TokenNotAvailable", inputs: [] },
    { type: "error", name: "TransferFailed", inputs: [] },
    { type: "error", name: "ZeroAmount", inputs: [] },
    { type: "error", name: "amountSharesInvalid", inputs: [] },
  ] as const;
