export const LendingPoolRouterAbi = [
      {
        type: "constructor",
        inputs: [
          { name: "_lendingPool", type: "address", internalType: "address" },
          { name: "_factory", type: "address", internalType: "address" },
          {
            name: "_collateralToken",
            type: "address",
            internalType: "address",
          },
          { name: "_borrowToken", type: "address", internalType: "address" },
          { name: "_ltv", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "accrueInterest",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "addressPositions",
        inputs: [{ name: "", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "borrowDebt",
        inputs: [
          { name: "_amount", type: "uint256", internalType: "uint256" },
          { name: "_user", type: "address", internalType: "address" },
        ],
        outputs: [
          { name: "protocolFee", type: "uint256", internalType: "uint256" },
          { name: "userAmount", type: "uint256", internalType: "uint256" },
          { name: "shares", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "borrowToken",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "calculateBorrowRate",
        inputs: [],
        outputs: [
          { name: "borrowRate", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "calculateSupplyRate",
        inputs: [],
        outputs: [
          { name: "supplyRate", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateralToken",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "createPosition",
        inputs: [{ name: "_user", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "emergencyResetPosition",
        inputs: [{ name: "_user", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "factory",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getUtilizationRate",
        inputs: [],
        outputs: [
          { name: "utilizationRate", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "lastAccrued",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "lendingPool",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "liquidatePosition",
        inputs: [
          { name: "_user", type: "address", internalType: "address" },
          { name: "_repayAmount", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "ltv",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "reduceUserCollateral",
        inputs: [
          { name: "_user", type: "address", internalType: "address" },
          { name: "_amount", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "repayWithSelectedToken",
        inputs: [
          { name: "_shares", type: "uint256", internalType: "uint256" },
          { name: "_user", type: "address", internalType: "address" },
        ],
        outputs: [
          { name: "", type: "uint256", internalType: "uint256" },
          { name: "", type: "uint256", internalType: "uint256" },
          { name: "", type: "uint256", internalType: "uint256" },
          { name: "", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "setLendingPool",
        inputs: [
          { name: "_lendingPool", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "supplyCollateral",
        inputs: [
          { name: "_user", type: "address", internalType: "address" },
          { name: "_amount", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "supplyLiquidity",
        inputs: [
          { name: "_amount", type: "uint256", internalType: "uint256" },
          { name: "_user", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "totalBorrowAssets",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalBorrowShares",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupplyAssets",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupplyShares",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "userBorrowShares",
        inputs: [{ name: "", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "userCollateral",
        inputs: [{ name: "", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "userSupplyShares",
        inputs: [{ name: "", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "withdrawCollateral",
        inputs: [
          { name: "_amount", type: "uint256", internalType: "uint256" },
          { name: "_user", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "withdrawLiquidity",
        inputs: [
          { name: "_shares", type: "uint256", internalType: "uint256" },
          { name: "_user", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "EmergencyPositionReset",
        inputs: [
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PositionLiquidated",
        inputs: [
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "sharesRemoved",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
          {
            name: "debtRepaid",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      { type: "error", name: "InsufficientCollateral", inputs: [] },
      { type: "error", name: "InsufficientLiquidity", inputs: [] },
      { type: "error", name: "InsufficientShares", inputs: [] },
      { type: "error", name: "NotFactory", inputs: [] },
      { type: "error", name: "NotLendingPool", inputs: [] },
      { type: "error", name: "PositionAlreadyCreated", inputs: [] },
      { type: "error", name: "ZeroAmount", inputs: [] },
    
] as const;
